### ISSUE TITLE
Route.js

### ISSUE THREAD

**Issue by z639** [rishavs/Verdin#1]
Hi,

Maybe I'm missing something, but looking through your code... at which point is services/Router.js imported and being used ? 

It seems to me that the app.js has and is doing all the router work here ?

Thanks.

**Comment by rishavs** [comment]
Thats my bad. Its not integrated at all. At one point I wanted to separate out the router. But then dropped out the idea as my router is just a dozen lines. I forgot to delete the router js file.

The actual code is in app.js
